import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

const HomeCSS = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6739B7',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#6739B7',
    fontFamily: 'DMSans-Bold',
    lineHeight: 24,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  header: {
    backgroundColor: '#6739B7',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 30,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 220,
  },
  headerBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: width,
    height: 235,
    opacity: 0.4,
  },
  headerOverlay: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
  },
  topCornerIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
  },
  cornerIcon: {
    width: 36,
    height: 36,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(10px)',
  },
  profileIcon: {
    width: 32,
    height: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(8px)',
  },
  helpIcon: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bankInfoSection: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginTop: 20,
  },
  bankLogo: {
    width: 60,
    height: 60,
    backgroundColor: 'rgba(175, 126, 207, 0.3)',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(10px)',
    marginBottom: 16,
  },
  bankName: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'DMSans-Bold',
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 8,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  bankCode: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: 'DMSans-Medium',
    lineHeight: 18,
    textAlign: 'center',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -20,
  },
  collectionCard: {
    margin: 20,
    marginTop: 30,
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    shadowColor: '#6739B7',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  collectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  collectionHeaderText: {
    fontSize: 16,
    color: '#1F2937',
    marginLeft: 8,
    fontFamily: 'DMSans-Bold',
    lineHeight: 22,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  collectionAmount: {
    fontSize: 36,
    color: '#6739B7',
    fontFamily: 'DMSans-Medium',
    lineHeight: 44,
    marginBottom: 8,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  collectionSubtext: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 24,
    fontFamily: 'DMSans-Medium',
    lineHeight: 20,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  collectionActions: {
    flexDirection: 'row',
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6739B7',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    minHeight: 48,
  },
  secondaryButton: {
    backgroundColor: 'rgba(103, 57, 183, 0.1)',
    borderWidth: 1,
    borderColor: '#6739B7',
  },
  actionButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'DMSans-Bold',
    lineHeight: 20,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  secondaryButtonText: {
    color: '#6739B7',
    fontFamily: 'DMSans-Bold',
  },
  statsContainer: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    minHeight: 120,
    justifyContent: 'center',
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statNumber: {
    fontSize: 24,
    color: '#1F2937',
    fontFamily: 'DMSans-Bold',
    lineHeight: 32,
    marginBottom: 4,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  statLabel: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    fontFamily: 'DMSans-Bold',
    lineHeight: 16,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
});

export default HomeCSS;